package it.generic_service_adapter.domain.orfani;

import java.time.LocalDateTime;

/**
 * Internal model of one {@code orphan_movement} row. Plain value object, no persistence annotation.
 *
 * @param id surrogate id, generated by the caller when the movement is first held
 * @param sourceTopic inbound Kafka topic the movement was consumed from
 * @param sourcePartition inbound Kafka partition, for traceability
 * @param sourceOffset inbound Kafka offset, for traceability
 * @param messageKey inbound message key ({@code accountId})
 * @param transactionId business transaction id carried by the movement event
 * @param userId {@code userId} referenced by the movement, not yet confirmed against the registry
 * @param accountId {@code accountId} referenced by the movement, not yet confirmed against the
 *     registry
 * @param direction {@code CREDIT | DEBIT}
 * @param rawPayload original JSON of the movement, kept for reconstruction and for the E4 case
 *     record
 * @param state {@code HELD | RESOLVED | EXPIRED}
 * @param attempts number of {@code OrphanReprocessor} passes that have inspected this row
 * @param receivedAt UTC wall-clock timestamp, when the movement was first held
 * @param holdDeadline UTC wall-clock timestamp, {@code receivedAt + holdTimeout}
 * @param lastCheckedAt UTC wall-clock timestamp of the last {@code OrphanReprocessor} pass over
 *     this row; {@code null} until the first check
 */
public record OrphanMovementRecord(
    String id,
    String sourceTopic,
    int sourcePartition,
    long sourceOffset,
    String messageKey,
    String transactionId,
    String userId,
    String accountId,
    String direction,
    String rawPayload,
    OrphanState state,
    int attempts,
    LocalDateTime receivedAt,
    LocalDateTime holdDeadline,
    LocalDateTime lastCheckedAt) {}
