package it.generic_service_adapter.domain.casistica;

import it.generic_service_adapter.domain.model.ErrorCategory;
import java.time.LocalDateTime;

/**
 * Internal model of one {@code case_record} row. Plain value object, no persistence annotation.
 *
 * @param id surrogate id, generated by the caller when the case record is created
 * @param createdAt UTC wall-clock timestamp, partition column ({@code PARTITION BY RANGE
 *     (TO_DAYS(created_at))})
 * @param caseState {@code PENDING_REPORT | IN_REPORT | REPORTED}
 * @param reportFileId logical reference to {@code report_file.id} (no FK, {@code case_record} is
 *     partitioned); {@code null} while {@code PENDING_REPORT}
 * @param errorCategory {@code E1..E7}
 * @param errorDetail technical exception detail, not masked; may be {@code null} for an
 *     expired-orphan (E4) case record with no exception
 * @param sourceTopic inbound Kafka topic the failing message was consumed from
 * @param sourcePartition inbound Kafka partition, for traceability
 * @param sourceOffset inbound Kafka offset, for traceability
 * @param messageKey inbound message key
 * @param userId {@code userId}, when extractable from the failing payload
 * @param accountId {@code accountId}, when extractable from the failing payload
 * @param transactionId transaction id, when extractable from the failing payload (movements only)
 * @param processingId correlation id assigned to this inbound message at ingestion
 * @param attempts retry attempts already made before landing here (E3/E7), 0 for non-retriable/E4
 * @param rawPayload full original JSON; text in DB, XML-escaped when embedded in the report
 * @param detectedAt UTC wall-clock timestamp, when the failure/expiry that created this row was
 *     detected
 * @param firstFailureAt UTC wall-clock timestamp, first failure (may predate {@code detectedAt} for
 *     retry exhaustion, E3/E7)
 * @param lastFailureAt UTC wall-clock timestamp, most recent failure
 * @param stateChangedAt UTC wall-clock timestamp, last {@code case_state} transition
 */
public record CaseRecord(
    String id,
    LocalDateTime createdAt,
    CaseState caseState,
    String reportFileId,
    ErrorCategory errorCategory,
    String errorDetail,
    String sourceTopic,
    int sourcePartition,
    long sourceOffset,
    String messageKey,
    String userId,
    String accountId,
    String transactionId,
    String processingId,
    int attempts,
    String rawPayload,
    LocalDateTime detectedAt,
    LocalDateTime firstFailureAt,
    LocalDateTime lastFailureAt,
    LocalDateTime stateChangedAt) {}
