-- V1__schema.sql
--
-- Baseline schema for the generic-service-adapter data model (MySQL 8.0),
-- see docs/architettura/modello-dati.md (source of truth, read it side by
-- side with this file) and:
--   - ADR 0010 (Flyway)
--   - ADR 0011 (Spring Data JDBC access)
--   - ADR 0014 (anag_user 1:N anag_account, additive merge)
--
-- Renamed from the WP0 placeholder `V1__baseline.sql`: that file was a
-- no-op documenting that the real schema would land as a later version.
-- Since no migration has ever shipped to a real environment yet (WP0/WP1
-- only ran this locally against throwaway dev databases), replacing V1
-- in place is safe and reads better as the actual baseline than adding a
-- V2 on top of a no-op V1. From here on, schema changes are additive
-- V2__*.sql, V3__*.sql, ... per ADR 0010.
--
-- Conventions used throughout this file:
--   - `DATETIME(6)` (never `TIMESTAMP`) for every temporal column: the
--     application always writes UTC wall-clock values, `DATETIME` performs
--     no implicit session-timezone conversion and has no year-2038 limit.
--   - `CHAR(36)` for UUID-shaped surrogate ids (orphan_movement.id,
--     case_record.id, report_file.id, audit.id, and the CHAR(36) columns
--     that reference them logically). [ASSUMPTION] `BINARY(16)` would be
--     more compact (16 vs 36 bytes) and marginally faster to index, but
--     it is opaque in MySQL Workbench (the confirm gate for this WP is a
--     human reviewing the schema there) and requires UUID_TO_BIN/BIN_TO_UUID
--     conversions on every read/write. Readability during review wins here;
--     revisit if row-count/storage pressure on `audit` (~8.6M rows/day)
--     ever becomes a real bottleneck.
--   - `VARCHAR(255)` for the natural/business string ids and enum-like
--     status columns, exactly as sized in modello-dati.md's erDiagram.
--   - `JSON` for the two `report_file` aggregate-count columns.
--   - `LONGTEXT` for the raw original-payload columns; `TEXT` for
--     `case_record.error_detail` (unbounded technical exception text, not
--     the full payload) — sizes match modello-dati.md verbatim.
--   - Every table/column carries a `COMMENT` with the one-line semantics
--     from modello-dati.md, so a reviewer in Workbench does not need the
--     markdown open side by side.
--   - `ENGINE=InnoDB` (required for FKs and partitioning) and
--     `utf8mb4`/`utf8mb4_0900_ai_ci` (MySQL 8.0 default) are set explicitly
--     on every table rather than relied upon implicitly.

-- ---------------------------------------------------------------------------
-- Anagraphic registry: anag_user (1) --- (N) anag_account, real FK (ADR 0014)
-- ---------------------------------------------------------------------------

CREATE TABLE anag_user (
    user_id       VARCHAR(255)  NOT NULL
        COMMENT 'natural key, the userId carried by the inbound registry events',
    last_version  BIGINT        NOT NULL
        COMMENT 'latest applied event version (CAS on this column, RF-31)',
    status        VARCHAR(255)  NOT NULL
        COMMENT 'normalized enum: ACTIVE | SUSPENDED | CLOSED',
    updated_at    DATETIME(6)   NOT NULL
        COMMENT 'UTC, set to the app clock on every successful CAS update',
    PRIMARY KEY (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='One row per userId whose registry the adapter has consumed (RNF-13, permanent retention).';

CREATE TABLE anag_account (
    account_id     VARCHAR(255)  NOT NULL
        COMMENT 'natural key, the accountId carried inline in accounts[] (ADR 0014)',
    user_id        VARCHAR(255)  NOT NULL
        COMMENT 'owning userId, real FK to anag_user.user_id',
    status         VARCHAR(255)  NOT NULL
        COMMENT 'normalized account enum, updated to the latest event that lists this account',
    first_seen_at  DATETIME(6)   NOT NULL
        COMMENT 'UTC, first time this accountId was observed in any event',
    PRIMARY KEY (account_id),
    KEY idx_anag_account_user (user_id),
    CONSTRAINT fk_anag_account_user
        FOREIGN KEY (user_id) REFERENCES anag_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='One row per seen accountId (1:N to anag_user, real FK). Additive merge: never removed by a later event that omits it (ADR 0014, §4.4).';

-- ---------------------------------------------------------------------------
-- Orphan movement holding area (no FK on purpose: userId/accountId may not
-- exist yet in the registry, that is the whole point of this table)
-- ---------------------------------------------------------------------------

CREATE TABLE orphan_movement (
    id                CHAR(36)      NOT NULL
        COMMENT 'surrogate id, generated by the app on hold',
    source_topic      VARCHAR(255)  NOT NULL
        COMMENT 'inbound Kafka topic the movement was consumed from',
    source_partition  INT           NOT NULL
        COMMENT 'inbound Kafka partition, for traceability',
    source_offset     BIGINT        NOT NULL
        COMMENT 'inbound Kafka offset, for traceability',
    message_key       VARCHAR(255)  NOT NULL
        COMMENT 'inbound message key (accountId)',
    transaction_id    VARCHAR(255)  NOT NULL
        COMMENT 'business transaction id carried by the movement event',
    user_id           VARCHAR(255)  NOT NULL
        COMMENT 'userId referenced by the movement, not yet confirmed against the registry',
    account_id        VARCHAR(255)  NOT NULL
        COMMENT 'accountId referenced by the movement, not yet confirmed against the registry',
    direction         VARCHAR(255)  NOT NULL
        COMMENT 'CREDIT | DEBIT',
    raw_payload       LONGTEXT      NOT NULL
        COMMENT 'original JSON of the movement, kept for reconstruction and for the E4 case record',
    state             VARCHAR(255)  NOT NULL
        COMMENT 'HELD | RESOLVED | EXPIRED',
    attempts          SMALLINT      NOT NULL DEFAULT 0
        COMMENT 'number of OrphanReprocessor passes that have inspected this row',
    received_at       DATETIME(6)   NOT NULL
        COMMENT 'UTC, when the movement was first held',
    hold_deadline     DATETIME(6)   NOT NULL
        COMMENT 'UTC, received_at + gsa.orphan-hold.hold-timeout',
    last_checked_at   DATETIME(6)   NULL
        COMMENT 'UTC, last OrphanReprocessor pass over this row; NULL until the first check',
    PRIMARY KEY (id),
    KEY idx_orphan_due (state, hold_deadline)
        COMMENT 'OrphanReprocessor: select HELD rows due for a check',
    KEY idx_orphan_key (state, account_id)
        COMMENT 'lookup HELD rows by account'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='One row per movement whose userId/accountId is not (yet) in the registry (ADR 0003). No FK: the point of this table is that the registry rows may not exist yet.';

-- ---------------------------------------------------------------------------
-- Case-record store: partitioned by created_at (retention window), so the
-- PK must include the partition column and report_file_id is a LOGICAL
-- reference (no FK allowed on a partitioned table in MySQL 8.0).
-- ---------------------------------------------------------------------------

CREATE TABLE case_record (
    id                CHAR(36)      NOT NULL
        COMMENT 'surrogate id, generated by the app when the case record is created',
    created_at        DATETIME(6)   NOT NULL
        COMMENT 'UTC, partition column (PARTITION BY RANGE (TO_DAYS(created_at)))',
    case_state        VARCHAR(255)  NOT NULL
        COMMENT 'PENDING_REPORT | IN_REPORT | REPORTED (guarded UPDATE ... WHERE case_state = :expected)',
    report_file_id    CHAR(36)      NULL
        COMMENT 'logical reference to report_file.id (no FK: case_record is partitioned), NULL while PENDING_REPORT',
    error_category    VARCHAR(255)  NOT NULL
        COMMENT 'E1..E7',
    error_detail      TEXT          NULL
        COMMENT 'technical exception detail, not masked; may be NULL for an expired-orphan (E4) case record with no exception',
    source_topic      VARCHAR(255)  NOT NULL
        COMMENT 'inbound Kafka topic the failing message was consumed from',
    source_partition  INT           NOT NULL
        COMMENT 'inbound Kafka partition, for traceability',
    source_offset     BIGINT        NOT NULL
        COMMENT 'inbound Kafka offset, for traceability',
    message_key       VARCHAR(255)  NOT NULL
        COMMENT 'inbound message key',
    user_id           VARCHAR(255)  NULL
        COMMENT 'userId, when extractable from the failing payload (may be unknown for e.g. malformed JSON, E1)',
    account_id        VARCHAR(255)  NULL
        COMMENT 'accountId, when extractable from the failing payload',
    transaction_id    VARCHAR(255)  NULL
        COMMENT 'transaction id, when extractable from the failing payload (movements only)',
    processing_id     CHAR(36)      NOT NULL
        COMMENT 'correlation id assigned to this inbound message at ingestion',
    attempts          SMALLINT      NOT NULL DEFAULT 0
        COMMENT 'retry attempts already made before landing here (E3/E7), 0 for non-retriable / E4',
    raw_payload       LONGTEXT      NOT NULL
        COMMENT 'full original JSON; text in DB, XML-escaped when embedded in the report',
    detected_at       DATETIME(6)   NOT NULL
        COMMENT 'UTC, when the failure/expiry that created this row was detected',
    first_failure_at  DATETIME(6)   NOT NULL
        COMMENT 'UTC, first failure timestamp (may predate detected_at for retry exhaustion, E3/E7)',
    last_failure_at   DATETIME(6)   NOT NULL
        COMMENT 'UTC, most recent failure timestamp',
    state_changed_at  DATETIME(6)   NOT NULL
        COMMENT 'UTC, last case_state transition timestamp',
    PRIMARY KEY (id, created_at),
    KEY idx_case_pending (case_state, created_at)
        COMMENT 'ReportAssembler: select PENDING_REPORT case records in creation order',
    KEY idx_case_file (report_file_id)
        COMMENT 'logical join with report_file'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='Failed/expired inbound cases (E1..E7), state machine PENDING_REPORT -> IN_REPORT -> REPORTED. Composite PK (id, created_at): MySQL requires the partition column in every key on a partitioned table.'
PARTITION BY RANGE (TO_DAYS(created_at)) (
    -- [ASSUMPTION] modello-dati.md specifies the partitioning *mechanism*
    -- (`PARTITION BY RANGE (TO_DAYS(created_at))`, daily partitions,
    -- `DROP PARTITION` for expired ones with the E-record pre-check) but not
    -- how many partitions a migration should pre-create up front: creating
    -- and dropping the *daily* partitions on an ongoing basis is explicitly
    -- an operational job left to a later WP ("you only need the
    -- partitioning DDL itself here, not the pruning job"). This migration
    -- bootstraps a small window of daily partitions around the schema's
    -- introduction date plus a MAXVALUE catch-all, so inserts never fail
    -- before that job exists; the job is expected to split p_future into
    -- new daily partitions ahead of time and DROP the expired ones.
    PARTITION p_before_2026_09_01 VALUES LESS THAN (TO_DAYS('2026-09-01')),
    PARTITION p_2026_09_01 VALUES LESS THAN (TO_DAYS('2026-09-02')),
    PARTITION p_2026_09_02 VALUES LESS THAN (TO_DAYS('2026-09-03')),
    PARTITION p_2026_09_03 VALUES LESS THAN (TO_DAYS('2026-09-04')),
    PARTITION p_2026_09_04 VALUES LESS THAN (TO_DAYS('2026-09-05')),
    PARTITION p_2026_09_05 VALUES LESS THAN (TO_DAYS('2026-09-06')),
    PARTITION p_2026_09_06 VALUES LESS THAN (TO_DAYS('2026-09-07')),
    PARTITION p_2026_09_07 VALUES LESS THAN (TO_DAYS('2026-09-08')),
    PARTITION p_2026_09_08 VALUES LESS THAN (TO_DAYS('2026-09-09')),
    PARTITION p_2026_09_09 VALUES LESS THAN (TO_DAYS('2026-09-10')),
    PARTITION p_2026_09_10 VALUES LESS THAN (TO_DAYS('2026-09-11')),
    PARTITION p_2026_09_11 VALUES LESS THAN (TO_DAYS('2026-09-12')),
    PARTITION p_2026_09_12 VALUES LESS THAN (TO_DAYS('2026-09-13')),
    PARTITION p_2026_09_13 VALUES LESS THAN (TO_DAYS('2026-09-14')),
    PARTITION p_2026_09_14 VALUES LESS THAN (TO_DAYS('2026-09-15')),
    PARTITION p_future VALUES LESS THAN MAXVALUE
);

-- ---------------------------------------------------------------------------
-- Report file: the durable send queue towards the Vault, and the target of
-- case_record's logical reference. Not partitioned (low volume, batch DELETE
-- retention), so a real FK back from case_record would be possible in
-- principle but is intentionally not declared (case_record is the
-- partitioned side and MySQL 8.0 disallows FKs that touch a partitioned
-- table on either end for this kind of guarded-lifecycle reference; see
-- modello-dati.md "MySQL 8.0 redesigns" #3).
-- ---------------------------------------------------------------------------

CREATE TABLE report_file (
    id                   CHAR(36)       NOT NULL
        COMMENT 'surrogate id, also used as the transfer id towards the Vault (idempotent resend, RF-19/RF-20)',
    state                VARCHAR(255)   NOT NULL
        COMMENT 'PENDING_SEND | SENT | PURGED',
    window_from          DATETIME(6)    NOT NULL
        COMMENT 'UTC, start of the case-record time window included in this report',
    window_to            DATETIME(6)    NOT NULL
        COMMENT 'UTC, end of the case-record time window included in this report',
    environment          VARCHAR(255)   NOT NULL
        COMMENT 'environment the report was produced in (dev | prod)',
    adapter_version      VARCHAR(255)   NOT NULL
        COMMENT 'adapter build/version that produced the report',
    case_count           INT            NOT NULL
        COMMENT 'total case records included in this report',
    counts_by_category   JSON           NOT NULL
        COMMENT 'counts per errorCategory, e.g. {"E1": 3, "E4": 12}',
    counts_by_topic      JSON           NOT NULL
        COMMENT 'counts per sourceTopic',
    file_path            VARCHAR(1024)  NOT NULL
        COMMENT 'path of the generated XML file on the report volume',
    attempts             SMALLINT       NOT NULL DEFAULT 0
        COMMENT 'send attempts made so far towards the Vault',
    created_at           DATETIME(6)    NOT NULL
        COMMENT 'UTC, when ReportAssembler created this record and wrote the XML file',
    next_attempt_at      DATETIME(6)    NOT NULL
        COMMENT 'UTC, when ReportRunner should retry the send (now() + backoff after a failed attempt)',
    sent_at              DATETIME(6)    NULL
        COMMENT 'UTC, set after a 2xx response from the Vault',
    purge_after          DATETIME(6)    NULL
        COMMENT 'UTC, sent_at + retention (7 days default); after this the XML file is deleted from the volume and state moves to PURGED',
    PRIMARY KEY (id),
    KEY idx_report_queue (state, next_attempt_at)
        COMMENT 'ReportRunner: select the durable send queue (state <> SENT) due for a retry',
    KEY idx_report_purge (state, purge_after)
        COMMENT 'pruning job: select SENT rows whose purge_after has passed'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='One row per XML report sent to the Vault, state machine PENDING_SEND -> SENT -> PURGED (RF-32, RF-21, RF-36).';

-- ---------------------------------------------------------------------------
-- Audit: every published message (UserAccount and WalletMovement), the
-- physical traceability trail plus the movement skip-republish dedup.
-- Partitioned by published_date, so PK/UNIQUE must include it (MySQL 8.0
-- redesign #2); the movement dedup itself needs redesign #1 (generated
-- column, no partial unique index in MySQL). published_date is itself a
-- second generated column (day-truncated from published_at) so that (a) the
-- dedup key is at the calendar-day granularity documented in
-- modello-dati.md, and (b) partitioning directly on that same column keeps
-- every key that must satisfy the "partition column subset" rule (PK and
-- uq_audit_txn_dedup) trivially compliant.
-- ---------------------------------------------------------------------------

CREATE TABLE audit (
    id                CHAR(36)      NOT NULL
        COMMENT 'surrogate id, generated by the app for each published message',
    published_at      DATETIME(6)   NOT NULL
        COMMENT 'UTC, full-precision publish timestamp (traceability/ordering); not a key or partition column, see published_date',
    published_date    DATE
        GENERATED ALWAYS AS (DATE(published_at)) STORED
        COMMENT 'UTC calendar date derived from published_at; partition column and dedup-granularity column (see uq_audit_txn_dedup)',
    processing_id     CHAR(36)      NOT NULL
        COMMENT 'correlation id assigned to the inbound message at ingestion',
    source_topic      VARCHAR(255)  NOT NULL
        COMMENT 'inbound Kafka topic',
    source_partition  INT           NOT NULL
        COMMENT 'inbound Kafka partition, physical traceability (RNF-11)',
    source_offset     BIGINT        NOT NULL
        COMMENT 'inbound Kafka offset, physical traceability (RNF-11)',
    dest_topic        VARCHAR(255)  NOT NULL
        COMMENT 'UserAccount | WalletMovement (destination topic name)',
    message_type      VARCHAR(255)  NOT NULL
        COMMENT 'USER_ACCOUNT | WALLET_MOVEMENT',
    message_key       VARCHAR(255)  NOT NULL
        COMMENT 'published message key',
    transaction_id    VARCHAR(255)  NULL
        COMMENT 'movements only; NULL for USER_ACCOUNT rows',
    -- MySQL 8.0 redesign #1 (modello-dati.md): no partial/predicate unique
    -- index exists in MySQL, so the "movements only" dedup selectivity is
    -- expressed with a generated column that is NULL for every registry
    -- (USER_ACCOUNT) row; MySQL UNIQUE allows any number of NULLs, so those
    -- rows never participate in the UNIQUE (txn_dedup, published_date) below.
    -- [ASSUMPTION] declared VARCHAR(64) exactly as sized in
    -- modello-dati.md's erDiagram, even though transaction_id itself is
    -- VARCHAR(255): business transaction ids are expected to be short
    -- (e.g. UUID-formatted, 36 chars) opaque identifiers, not free text: a
    -- transaction_id longer than 64 chars would silently truncate in this
    -- generated column. Flagged for confirmation with analista-funzionale
    -- if transaction ids can legitimately exceed 64 characters.
    txn_dedup         VARCHAR(64)
        GENERATED ALWAYS AS (
            IF(message_type = 'WALLET_MOVEMENT', transaction_id, NULL)
        ) STORED
        COMMENT 'GENERATED: transaction_id when message_type = WALLET_MOVEMENT, else NULL (movement skip-republish dedup, ADR 0009)',
    user_id           VARCHAR(255)  NULL
        COMMENT 'registry only; NULL for WALLET_MOVEMENT rows',
    user_version      BIGINT        NULL
        COMMENT 'registry only; the event version that produced this UserAccount publication',
    PRIMARY KEY (id, published_date),
    KEY idx_audit_origin (source_topic, source_partition, source_offset)
        COMMENT 'non-unique on purpose (RNF-11): physical traceability lookup, not a dedup key',
    UNIQUE KEY uq_audit_txn_dedup (txn_dedup, published_date)
        COMMENT 'movement skip-republish at calendar-day granularity via the generated published_date column (day-truncated from published_at, UTC): an upstream replay of the same transaction_id on the same day is rejected regardless of the exact publish instant, matching modello-dati.md MySQL 8.0 redesigns #1'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='One row per message published downstream (UserAccount or WalletMovement). Composite PK (id, published_date): MySQL requires the partition column in every key on a partitioned table. ~8.6M rows/day at 100 msg/s.'
PARTITION BY RANGE COLUMNS (published_date) (
    -- [ASSUMPTION] same bootstrap-window rationale as case_record above:
    -- the daily create/drop partition maintenance is a later WP's
    -- scheduled job; this migration only bootstraps a small initial window
    -- plus a MAXVALUE catch-all partition. RANGE COLUMNS takes the
    -- published_date column's native DATE type directly, no TO_DAYS(...)
    -- wrapper needed (unlike case_record, which stays on RANGE (TO_DAYS(...))
    -- since it has no analogous day-granularity dedup key).
    PARTITION p_before_2026_09_01 VALUES LESS THAN ('2026-09-01'),
    PARTITION p_2026_09_01 VALUES LESS THAN ('2026-09-02'),
    PARTITION p_2026_09_02 VALUES LESS THAN ('2026-09-03'),
    PARTITION p_2026_09_03 VALUES LESS THAN ('2026-09-04'),
    PARTITION p_2026_09_04 VALUES LESS THAN ('2026-09-05'),
    PARTITION p_2026_09_05 VALUES LESS THAN ('2026-09-06'),
    PARTITION p_2026_09_06 VALUES LESS THAN ('2026-09-07'),
    PARTITION p_2026_09_07 VALUES LESS THAN ('2026-09-08'),
    PARTITION p_2026_09_08 VALUES LESS THAN ('2026-09-09'),
    PARTITION p_2026_09_09 VALUES LESS THAN ('2026-09-10'),
    PARTITION p_2026_09_10 VALUES LESS THAN ('2026-09-11'),
    PARTITION p_2026_09_11 VALUES LESS THAN ('2026-09-12'),
    PARTITION p_2026_09_12 VALUES LESS THAN ('2026-09-13'),
    PARTITION p_2026_09_13 VALUES LESS THAN ('2026-09-14'),
    PARTITION p_2026_09_14 VALUES LESS THAN ('2026-09-15'),
    PARTITION p_future VALUES LESS THAN (MAXVALUE)
);
