package it.generic_service_adapter.domain.publish;

import java.time.LocalDateTime;

/**
 * Internal model of one {@code audit} row: one per message published downstream. Plain value
 * object, no persistence annotation.
 *
 * @param id surrogate id, generated by the caller for each published message
 * @param publishedAt UTC wall-clock, full-precision publish timestamp (traceability/ordering); the
 *     day-truncated {@code published_date} dedup/partition column is derived by the database
 *     ({@code GENERATED ALWAYS AS (DATE(published_at))}), never computed here
 * @param processingId correlation id assigned to the inbound message at ingestion
 * @param sourceTopic inbound Kafka topic
 * @param sourcePartition inbound Kafka partition, physical traceability (RNF-11)
 * @param sourceOffset inbound Kafka offset, physical traceability (RNF-11)
 * @param destTopic {@code UserAccount | WalletMovement} (destination topic name)
 * @param messageType {@code USER_ACCOUNT | WALLET_MOVEMENT}
 * @param messageKey published message key
 * @param transactionId movements only; {@code null} for {@code USER_ACCOUNT} rows
 * @param userId registry only; {@code null} for {@code WALLET_MOVEMENT} rows
 * @param userVersion registry only; the event version that produced this {@code UserAccount}
 *     publication
 */
public record AuditRecord(
    String id,
    LocalDateTime publishedAt,
    String processingId,
    String sourceTopic,
    int sourcePartition,
    long sourceOffset,
    String destTopic,
    MessageType messageType,
    String messageKey,
    String transactionId,
    String userId,
    Long userVersion) {}
